### ISSUE TITLE
Installing with Mac OS X

### ISSUE THREAD

**Issue by markph0204** [matsoftware/swift-code-metrics#3]
How to install on Mac...

```
python3 -m .venv
source .venv/bin/activate
brew install graphviz
pip install swift-code-metrics
```

I would have added this to Wiki -- but it was not turned on ... couldn't access.

**Comment by matsoftware** [comment]
Hi Mark, thanks for flagging this out. Wiki should be accessible by everyone now.
Actually I don’t think you need to activate a python environment to install graphviz. `brew install graphiz` would just work. Have you tried it directly?

**Comment by markph0204** [comment]
Correct you do not need to create or activate the working virtualenv to install brew.  I was including complete steps.

**Comment by matsoftware** [comment]
I've created the Wiki and added the informations there:

https://github.com/matsoftware/swift-code-metrics/wiki

Thanks for raising the issue 👍

**Comment by AnarH93** [comment]
Hi, 

macOS 10.14.3

I had this: 
```
$ python3 -m .venv
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3: Relative module names not supported
$ source .venv/bin/activate
-bash: .venv/bin/activate: No such file or directory
```
Any ideas where I should run this or how to avoid such error?

**Comment by markph0204** [comment]
@AnarH93 I mistakenly freehand typed it wrong, please see the updated line:

`
python3 -m venv .venv
`
